
name: snap-dash # you probably want to 'snapcraft register <name>'
version: '0.0.1'
summary: Dash Coin node as a Snap package
description: |
  Dash Coin node as a Snap package

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  dash:
    command: bin/dashd
    daemon: simple

parts:
  dash:
    plugin: autotools
    source: https://github.com/dashpay/dash.git
    source-type: git
    source-branch: v0.12.1.x
    source-depth: 1
    configflags:
     - "--disable-wallet"
     - "--disable-tests"
     - "--disable-gui-tests"
     - "--disable-bench"
     - "--disable-ccache"
     - "--disable-zmq"
     - "--without-miniupnpc"
     - "--with-daemon"
     - "--enable-hardening"
    build-packages:
     - build-essential
     - libtool
     - autotools-dev
     - automake
     - pkg-config
     - libssl-dev
     - libevent-dev
     - bsdmainutils
     - libboost-system-dev
     - libboost-filesystem-dev
     - libboost-chrono-dev
     - libboost-program-options-dev
     - libboost-test-dev
     - libboost-thread-dev
